const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const solanaWeb3 = require('@solana/web3.js');
const db = require('../config/database');

// Build Anchor program: write files to temp directory, run `anchor build`, read .so binary
exports.buildProgram = async (rustFiles) => {
  // 确保 rustFiles 是有效的数组
  if (!rustFiles || !Array.isArray(rustFiles) || rustFiles.length === 0) {
    console.warn('No valid Rust files provided, creating a default program');
    rustFiles = [{
      name: 'lib.rs',
      content: `
use anchor_lang::prelude::*;

declare_id!("11111111111111111111111111111111");

#[program]
pub mod my_program {
    use super::*;
    
    pub fn initialize(ctx: Context<Initialize>) -> Result<()> {
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize {}
`
    }];
  }
  
  const tmpDir = path.join(__dirname, '../../tmp', `solana_${Date.now()}`);
  fs.mkdirSync(tmpDir, { recursive: true });
  
  // Create proper Anchor workspace structure
  const programsDir = path.join(tmpDir, 'programs', 'my_program');
  fs.mkdirSync(programsDir, { recursive: true });
  fs.mkdirSync(path.join(programsDir, 'src'), { recursive: true });
  
  // Create Anchor.toml with unique program ID
  const { Keypair } = require('@solana/web3.js');
  const anchorKeypair = Keypair.generate();
  const anchorProgramId = anchorKeypair.publicKey.toBase58();
  
  const anchorToml = `
[features]
seeds = false

[programs.localnet]
my_program = "${anchorProgramId}"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./keypair.json"
`;
  fs.writeFileSync(path.join(tmpDir, 'Anchor.toml'), anchorToml);
  
  // Create Cargo.toml in workspace root with resolver = "2" to fix the warning
  const rootCargoToml = `
[workspace]
members = [
    "programs/my_program",
]
resolver = "2"
`;
  fs.writeFileSync(path.join(tmpDir, 'Cargo.toml'), rootCargoToml);
  
  // Create program Cargo.toml with lib path and crate type
  // Updated to match anchor 0.27.0 dependencies
  const programCargoToml = `
[package]
name = "my_program"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.27.0"
anchor-spl = "0.27.0"
solana-program = "1.14.17"
`;
  fs.writeFileSync(path.join(programsDir, 'Cargo.toml'), programCargoToml);
  
  // Create keypair.json for wallet
  const keypairJson = '[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
  fs.writeFileSync(path.join(tmpDir, 'keypair.json'), keypairJson);
  
  // Create a Cargo.lock file with version 3 (compatible with current Rust toolchain)
  const cargoLock = `
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "my_program"
version = "0.1.0"
dependencies = [
 "anchor-lang 0.27.0",
 "solana-program 1.14.17",
]
`;
  fs.writeFileSync(path.join(tmpDir, 'Cargo.lock'), cargoLock);
  
  // Determine lib.rs content for Anchor build
  const defaultLibRs = `
use anchor_lang::prelude::*;
declare_id!("11111111111111111111111111111111");
#[program]
pub mod my_program { pub fn initialize(ctx: Context<Initialize>) -> Result<()> { Ok(()) } }
#[derive(Accounts)] pub struct Initialize { }
`;
  let libContent;
  if (Array.isArray(rustFiles) && rustFiles.length > 0 && rustFiles[0].content) {
    libContent = rustFiles[0].content;
  } else {
    console.warn('Using default lib.rs content');
    libContent = defaultLibRs;
  }
  const libRsPath = path.join(programsDir, 'src', 'lib.rs');
  fs.writeFileSync(libRsPath, libContent);
  console.log(`lib.rs written (${libContent.length} bytes) to ${libRsPath}`);
  
  // Log source directory for debugging
  console.log('Source directory contents:', fs.readdirSync(path.join(programsDir, 'src')));
  
  // Run anchor build with --locked flag to use the provided Cargo.lock
  await new Promise((resolve, reject) => {
    // Using "anchor build -- --locked" to pass the --locked flag to cargo
    exec('anchor build -- --locked', { cwd: tmpDir }, (err, stdout, stderr) => {
      if (err) {
        console.error('Anchor build error:', stderr);
        return reject(err);
      }
      console.log('Anchor build output:', stdout);
      resolve();
    });
  });
  
  // Read binary
  const soPath = path.join(tmpDir, 'target/deploy', 'my_program.so');
  const binary = fs.readFileSync(soPath);
  const programBinaryHex = binary.toString('hex');
  
  // Read IDL
  const idlPath = path.join(tmpDir, 'target/idl', 'my_program.json');
  const idlJson = JSON.parse(fs.readFileSync(idlPath, 'utf-8'));
  
  return { programBinaryHex, idlJson };
};

// Estimate fee using Solana connection
exports.estimateFee = async (programBinaryHex, network) => {
  const connection = new solanaWeb3.Connection(solanaWeb3.clusterApiUrl(network));
  const feeCalculator = await connection.getMinimumBalanceForRentExemption(Buffer.from(programBinaryHex, 'hex').length);
  return feeCalculator;
};

// Deploy program: upload binary and return programId, signature, logs
exports.deployProgram = async (programBinaryHex, network) => {
  const connection = new solanaWeb3.Connection(solanaWeb3.clusterApiUrl(network));
  const keypair = solanaWeb3.Keypair.generate();
  const programData = Buffer.from(programBinaryHex, 'hex');
  const tx = new solanaWeb3.Transaction();
  const { blockhash } = await connection.getLatestBlockhash();
  tx.recentBlockhash = blockhash;
  tx.add(
    solanaWeb3.SystemProgram.createAccount({
      fromPubkey: keypair.publicKey,
      newAccountPubkey: keypair.publicKey,
      lamports: await connection.getMinimumBalanceForRentExemption(programData.length),
      space: programData.length,
      programId: solanaWeb3.BPF_LOADER_PROGRAM_ID,
    }),
    solanaWeb3.Loader.load({
      connection,
      payer: keypair,
      program: keypair.publicKey,
      data: programData,
    })
  );
  const signature = await solanaWeb3.sendAndConfirmTransaction(connection, tx, [keypair]);
  const logs = await connection.getConfirmedTransaction(signature);
  return { programId: keypair.publicKey.toString(), signature, logs };
};

// Save deployment record
exports.saveDeployment = ({ userId, network, programId, signature, logs }) => {
  const sql = 'INSERT INTO solana_deployments (user_id, network, program_id, signature, logs, created_at) VALUES (?, ?, ?, ?, ?, NOW())';
  return db.execute(sql, [userId, network, programId, signature, JSON.stringify(logs)]);
};

// Get deployment by id
exports.getDeployment = (id) => {
  const sql = 'SELECT * FROM solana_deployments WHERE id = ?';
  return db.execute(sql, [id]).then(([rows]) => rows[0]);
}; 